### ISSUE TITLE
Allow Listener-interfaces with more than 1 method

### ISSUE THREAD

**Issue by tomivirkki** [wolfie/Blackboard#6]
It would be awesome if I could have a Listener interface with multiple methods observing Events. For Example;

public interface ThreadViewListener extends Listener {
    void addAttachment(final AddAttachmentEvent event);

```
void removeAttachment(final RemoveAttachmentEvent event);

void resetInput(final ResetInputEvent event);
```

}

Then I wouldn't have to write a Listener extension for each individual Event I want to observe.

**Comment by wolfie** [comment]
[05978a51a36be6a123dde98c0d00df4a49885927]
